### ISSUE TITLE
Remove Me From Maintainers List

### ISSUE THREAD

**Issue by alexfinnarn** [backdrop-contrib/devel_debug_log#1]
I no longer work on Backdrop projects and can't see myself doing so in the future.

**Comment by docwilmot** [comment]
That sounds like a dissatisfied customer. Care to say why?

**Comment by alexfinnarn** [comment]
https://github.com/backdrop-ops/contrib/issues/316

I just don't work on the stuff anymore. I like to be 100% there or not. Just the way I am, I guess. Keeping things tidy. I'm not dissatisfied, just moving on.
